version: '3.8'

services:
  frontend:
    build:
      context: ./N04Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./N04Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./N04Backend/.env
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db  # Maps local ./mongo-data folder to MongoDB's data directory
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
